Feature/4 0.12 upgrade
terraform-google-modules/terraform-google-endpoints-dns pull request #5
Opened 2019-12-02 22:15 UTC by taylorludwig

Fixes #4 

Root module was already upgraded but example was missing. 

Added `Compatibility` to readme

Added the `required_providers` for `google` to `2.0` version as I noticed some errors during a plan when it defaulted to 3.0 for the example.

2019-12-02 22:17 UTC, taylorludwig commented
Merging into `aaron-lane-0.12` to boil up PR #3

2019-12-10 16:43 UTC, aaron-lane requested changes
Thanks @taylorludwig. Can you move the compatibility note to the root README?

2019-12-10 16:43 UTC, aaron-lane commented on versions.tf
> +    google = "~> 2.19.0"
We should pin required providers at the minor level to ensure backward compatible updates can be pulled in without a module release.

```suggestion
    google = "~> 2.19"
```

2019-12-10 16:43 UTC, aaron-lane commented on examples/gce-acme/main.tf
>    auto_create_subnetworks = "false"
```suggestion
  auto_create_subnetworks = false
```

2019-12-10 16:43 UTC, aaron-lane commented on examples/gce-acme/main.tf
> +  region = var.region
The region should only be passed to modules and resources so let's just drop it from here.

2019-12-16 17:51 UTC, aaron-lane approved these changes

2019-12-16 17:52 UTC, merged